### ISSUE TITLE
jquery version

### ISSUE THREAD

**Issue by YvonneD** [payalord/xZoom#1]
The jquery embed link doen't work. And the latest 3.1.0 version doesn't apply showing the "Uncaught TypeError: a.indexOf is not a function" .   The version 2.1.0 works.  
update hopefully :)

**Comment by payalord** [comment]
I'll review this today, thanks. Probably patch will comes up in a day.

**Comment by lastobelus** [comment]
[selector was also removed](https://api.jquery.com/selector/)

**Comment by payalord** [comment]
By investigating this issue, i remembered that i have implemented long time ago - safe condition for `.selector` in case if by some reason it will not be available. So even if `.selector` is deprecated, xZoom still work. But just a little different.

# Example
Let say we have next initialization code:
```
$(".xzoom, .xzoom-gallery").xzoom();
```
Then
## With .selector available
xZoom will take only first image of the class `.xzoom` as main source image, then will ignore all other images of the class `.xzoom`, and starting from second class `.xzoom-gallery` it will use all of the images as thumbnails.

## Without .selector available
xZoom will take only first image of the class `.xzoom` as main source image, all other images of the class `.xzoom`, plus all images from the class `.xzoom-gallery` will be used as thumbnails.

So in case if class `.xzoom` is used only for main source image and for thumbnails is used only class `.xzoom-gallery`. Like dedicated - one class for main image, another for thumbnails. Then everything works fine without errors and as usual.
