### ISSUE TITLE
Smooth options dependent on each other and zero value bug

### ISSUE THREAD

**Issue by payalord** [payalord/xZoom#10]
Need to remove dependency of smooth options from each other. Setting value zero on one of them must not affect other smooth functionality.

Plus to this. Zero value is acceptable value. Need to fix any issues if present, regard zero value, on smooth and other options where it is available to use zero values.

**Comment by ermushko** [comment]
Knock knock! :) Don't forget about us! ;)

**Comment by payalord** [comment]
You right lol, trying to do much stuff right now, but thanks for reminding me of this. This issue possibly can be fixed fast. Just need to schedule time for this.
