### ISSUE TITLE
Touch move instead of click on mobile devices

### ISSUE THREAD

**Issue by ermushko** [payalord/xZoom#11]
Actually it is not an issue, but a usability problem. Can't we move big image while user drags lens on a preview? Now you must point-and-click inside a small preview to move a bit to the sides to view more of it, and you won't do it from the first try. I use "inside" setting and my preview is a click area, so users can't see where they need to click for viewing what they want. I think it should be like we move mouse cursor now on a desktop. 

Thank you.

**Comment by payalord** [comment]
You mean you want to assign "track movement event" from original image area to preview window? I'll see what approach is possible to do on this issue today.

**Comment by ermushko** [comment]
1. we click image preview
2. original shows up a) on the the side b) above preview image (inside setting)
3. we can touch and move finger above a) preview image b) orginal image (inside setting)
4. original images moves as we move finger

For "inside" setting it will look like we're viewing zoomed photo on a smartphone in stock apps.

**Comment by payalord** [comment]
https://payalord.github.io/xZoom/
Check "With Magnific Pop-up" example on this page from mobile device. When you first time tap on zoom, preview opens into fullscreen. If you drag it, image will move. You need the same like this? (btw double tap opens magnific on mobile device after zoom is opened).

Mobile guestures is different from desktop mouse events. To achieve this, I used there hammer.js plugin which is one of the coolest plugin to work with mobile gestures like tap and finger drag on the screen. I can show you the code on how to integrate xZoom with hammer.js or any other mobile gestures library if you wish.

**Comment by ermushko** [comment]
Even in "standart" example it is what I need... But my page doesn't work the same way. It means something is wrong with the settings. Thank you, I'll check them.

*UPD*
It's not the settings... Examples use some alpha version of xzoom.js?

**Comment by payalord** [comment]
No, they using latest version of xZoom. When patch is coming up, i'm updating xzoom js files everywhere, on examples too (if I didn't forgot that).

The thing is, that xZoom doesn't have native support of mobile gestures. But instead xZoom have all required API to be integrated with any available mobile gesture library. Why it is done this way - because of flexibility, people can already have on their pages their own mobile libraries, which already have all needed functionality to work with touch devices. And then they can integrate their libraries with xZoom in this case.

Here is an example on how to implement xZoom with popular hammer.js library version 1.*:

### Header section of HTML
```HTML
<link type="text/css" rel="stylesheet" media="all" href="/css/xzoom.css" />

<script type="text/javascript" src="/js/jquery-1.9.0.min.js"></script>
<script type="text/javascript" src="/js/jquery.hammer.js"></script>
<script type="text/javascript" src="/js/xzoom.min.js"></script>
```

### JS code in header
```javascript
(function ($) {
  $(document).ready(function() {
    var xzoom = $('.xzoom, .xzoom-gallery').xzoom(); // <-- Your options here
    
    var isTouchSupported = 'ontouchstart' in window;
    if (isTouchSupported) { // Only for touch devices
      xzoom.eventunbind();
    
      $('.xzoom:first').hammer().on("tap", function(event) { // On tap (like click) open zoom
        event.pageX = event.gesture.center.pageX;
        event.pageY = event.gesture.center.pageY;

        xzoom.eventmove = function(element) {
          element.hammer().on('drag', function(event) { // On drag (like mousemove)
            event.gesture.preventDefault();
            event.pageX = event.gesture.center.pageX;
            event.pageY = event.gesture.center.pageY;
            xzoom.movezoom(event);
          });
        }

        xzoom.eventleave = function(element) {
          element.hammer().on('tap', function(event) { // On tap when zoom opened (mouseleave)
            xzoom.closezoom();
          });
        }
        
        xzoom.openzoom(event);
      });
    }
  });
})(jQuery);
```

**Comment by ermushko** [comment]
Wow... I thank you so much for such a detailed answer! I'll definitely give it a try!

**Comment by payalord** [comment]
No problem, let me know if you have any other questions.
