### ISSUE TITLE
Fancybox 3 integration bug

### ISSUE THREAD

**Issue by Mecadeca** [payalord/xZoom#14]
Hi,
First of all thank you for sharing this excelent jquery pluggin.

I've been testing it today, and have set it up just right, but when i use Fancybox integration using version 3, it displays the path and name of the picture instead of the actual picture... Using Fancybox 2.0.5 it works as intended (the only issue with version 2 is losing the white border for some reason).

You can see that behavior in this URL on the "With Fancy Box" section: http://www.jqueryscript.net/demo/Feature-rich-Product-Gallery-With-Image-Zoom-xZoom/ (that page uses Fancybox version 3.0.47)

Is this a xZoom or a Fancybox 3 bug?

Thanks in advanced,
Jorge Chaves

**Comment by payalord** [comment]
Looks like they changed how the function `$.fancybox.open` works. I'll test it and show you how to deal with this little bit later today.

**Comment by payalord** [comment]
Ok, on that demo page, in [setup.js](http://www.jqueryscript.net/demo/Feature-rich-Product-Gallery-With-Image-Zoom-xZoom/js/setup.js) file, for Not Touch devices(i.e. not for mobiles) this:
```javascript
//Integration with fancybox plugin
$('#xzoom-fancy').bind('click', function(event) {
  var xzoom = $(this).data('xzoom');
  xzoom.closezoom();
  $.fancybox.open(xzoom.gallery().cgallery, {padding: 0, helpers: {overlay: {locked: false}}});
  event.preventDefault();
});
```

must be changed to this:
```javascript
//Integration with fancybox version 3 plugin
$('#xzoom-fancy').bind('click', function(event) {
  var xzoom = $(this).data('xzoom');
  xzoom.closezoom();
  var i, images = new Array();
  var gallery = xzoom.gallery().cgallery;
  for (i in gallery) {
    images[i] = {src: gallery[i]};
  }
  $.fancybox.open(images, {loop: false});
  event.preventDefault();
});
```

To work with fancybox version 3.

And for touch devices, this:
```javascript
function openfancy() {
  if (counter == 2) {
    xzoom.closezoom();
    $.fancybox.open(xzoom.gallery().cgallery);
  } else {
    xzoom.closezoom();
  }
  counter = 0;
}
```

Must be changed to this:
```javascript
function openfancy() {
  if (counter == 2) {
    xzoom.closezoom();
    var i, images = new Array();
    var gallery = xzoom.gallery().cgallery;
    for (i in gallery) {
      images[i] = {src: gallery[i]};
    }
    $.fancybox.open(images, {loop: false});
  } else {
    xzoom.closezoom();
  }
  counter = 0;
}
```

There is an option **loop** inside `$.fancybox.open` probably to control looping of images when you click on left and right arrows of fancybox3. You can switch it to **true** if you wish.
For other fancybox3 options please refer to options on [fancybox3 docs](http://fancyapps.com/fancybox/3/docs/#api) page.
About the white border problem of version 2.0.5, would be nice to see real life example, because hard to tell, is it CSS problem or some bug of fancybox.

**Comment by Mecadeca** [comment]
Hi Azat.

Its always a bummer when they change things and integrations stops working... But i have to say that you solution worked for me :) sorry not to have some integration that would work both on versions 2 and 3, but maybe in the future you can sort this out to work on both ;)

About the lack of white border on version 2, never mind... I didn't saw the "padding: 0" portion of the code... removing it (or inserting another value) solves the question :)

Thank you so much for all the help... i'll be making a contribution next week, and i urge anyone who reads this to do the same, to back this excellent jquery pluggin.

p.s. Is there a simple way to disable the zoom part, just to use this to multiple images browse with fancybox gallery? For instance, to products that doesn't have detail to be zoomed, or doesn't have good images to do so? I use the  zoomWidth and zoomHeight set to "0", but it would be nice to have some "on" or "off" switch in case we need it (even if this beats the principal purpose of this pluggin, but it would be useful for a number of scenarios) :)

Best regards,
Jorge Chaves

**Comment by payalord** [comment]
Thanks.
I think, I will create video tutorials with xZoom on youtube and sandbox inside this repository with all the examples available from that videos. This way would be more easier for people to see how to work with xZoom and it's advanced features.

About disable of zoom part - as a workaround with xZoom API for now is possible to unbind event of zoom opening depends on particular conditions and then again bind it back, i think. But, for sure, i think this needs to be added as a feature to switch "on" and "off" to make it more easier. Can you show me HTML markup on which cases needs exactly to switch zoom off and then back to on? Or how you do this approach? So I will figure out the best way to add switch functionality.
