### ISSUE TITLE
Mouseenter / Mouseleave Detection

### ISSUE THREAD

**Issue by psweeting1** [payalord/xZoom#18]
xZoom v1.0.8 

I've been reading the manual for a good while now and have been trying to detect when my mouse has entered the zoom container and when my mouse has left. 

```
     var instance = $('#main_image, .xzoom-gallery').xzoom({
            tint: '#333',
            adaptive: false,
            smoothZoomMove: 0,
            smoothLensMove: 0,
            smoothScale: 0,
            hover: true,
            title: true,
            defaultScale: 0
        });
```
This is my variable for instance.

```
//Example
instance.eventopen = function(element) {
  element.bind('mouseenter', instance.openzoom);
console.log('Entered');
}
```
This code above actually doesn't work and nothing is being returned to my console. 

```
instance.eventleave = function(element) {
  element.bind('mouseleave', instance.closezoom);
console.log('Leaving');
}
```
This code above works, but only when the mouse enters the zoomed image, but not when leaving which is weird as it feels reversed. 

I can't seem to work out how I can detect mouse enter and leave when zooming. I need images on my webpage to hide while I'm using xZoom and then reappear when I'm not using xZoom.

**Comment by payalord** [comment]
Try this:
```javascript
instance.eventleave = function(element) {
    element.bind('mouseleave', function(event) {
        instance.closezoom();
        console.log('Leaving');
    });
};
```

And btw you also can use `xon` and `xoff` functions instead of `bind/unbind` or `on/off` of jquery. Those 2 i have created as crossplatform jQuery `on` and `off`, so xon and xoff will work on any jQuery version. So the function changes a little with `xon` and `xoff`:

```javascript
instance.eventleave = function(element) {
    element.xon('mouseleave', function(event) {
        instance.closezoom();
        console.log('Leaving');
    });
};
```

`xon` and `xoff` is undocumented yet.

**Comment by payalord** [comment]
Oh and one more thing, instead of `eventopen` you better catch `Entered` on eventclick. Like this:

```javascript
xzoom.eventclick = function(element) {

  console.log('Entered');
          
  element.xon('click', function(event) {
    $('#main_image').trigger('click');
  });
}
```

**Comment by psweeting1** [comment]
Great that does the trick! Thank you very much for your help. I spent way to much time trying to solve this problem.
