### ISSUE TITLE
xZoom with Magnific Popup counter always start from 1

### ISSUE THREAD

**Issue by irenefelita12** [payalord/xZoom#19]
![image](https://user-images.githubusercontent.com/22439051/29822096-8368f7b6-8cf4-11e7-930e-20369abf86e8.png)
Eventhough I click on the third thumbnail and it pops up correct image, the counter always start from 1.
This bug doesnot happen on magnific popup gallery itself.
Does anyone have any fix or update for this?

**Comment by irenefelita12** [comment]
I ended up using this

```
var gallery = xzoom.gallery().ogallery; //get original gallery with start index 0
var i, images = new Array();
    for (i in gallery) {
        images[i] = {src: gallery[i], title: thumb[i].title};
    }


$.magnificPopup.open({
        items: images,
        mainClass: 'mfp-pdp', 
        preloader: false, 
        type:'image',
        gallery: {
            enabled: true
        },
        image: {
            titleSrc: 'title'
        }
    }, xzoom.gallery().index);
```

**Comment by payalord** [comment]
Thanks, for sharing your solution. I just didn't noticed there were a counter.
