### ISSUE TITLE
Destroying and reinitialising xZoom instance with new images

### ISSUE THREAD

**Issue by benthorndycraft** [payalord/xZoom#20]
I am using xZoom as a product image slider. 

When certain buttons on my interface are clicked I need my xZoom slider to dynamically update the slider, removing old images and adding new images when necessary.

For example:
There are 2 red product images and 3 blue product images.

Slider has 2 images of red products loaded. 
If I click on the "Blue" button I need the red image slides to be updated/removed and 3 new blue image slides to be added.

I have tried to trigger your destroy method by accessing the slide instance and running the function:
  
```  
instance = $(".xzoom, .xzoom-gallery").data("xzoom"); 
instance.destroy();
```

However the slider still continues to function.

What is the best method to destroy and/or update the slider with the new images in the cleanest way possible?

Thanks for your time, this is a great plugin!

**Comment by payalord** [comment]
To destroy you can try this one:
```javascript
$('.xzoom:first').data("xzoom").destroy();
$('.xzoom-gallery').each(function() {
    var link = $(this).parent();
    link.xoff('mouseenter');
    link.xoff('click');
    delete link;
});
```

And to add new thumb to existing xzoom instance possible to use `xappend` function:
```javascript
var instance = $('.xzoom:first').data("xzoom");
$(".xzoom-gallery").each(function() {
    instance.xappend($(this));
});
```

But I think you don't need to manually use `xappend` in your case if first you destroy xzoom completely. Because on new re-initialization of xzoom it will be done automatically.

**Comment by benthorndycraft** [comment]
Thanks for the swift reply. That works! Another question, is there an api method or way of swapping to a particular slide? For instance, initialise xZoom and then change to a image based on selected index or slide id/class.

**Comment by payalord** [comment]
Sorry I don't think there is special API exists for this purpose, but swapping happens when link of thumbnails in the slider was triggered on click or mouseenter(if hover option is set to true). So we always can use standard jQuery to swap for the needed particular slide:

```javascript
//Triggering click on 3 slide by their index starting from 0
$('.xzoom-gallery').eq(3).parent().trigger('click');
```
