### ISSUE TITLE
Lens error when on certain image size

### ISSUE THREAD

**Issue by irenefelita12** [payalord/xZoom#21]
In this case I use image size for preview (in src attribute) is 300x226 while image size for xoriginal attribute is 400x302

![image](https://user-images.githubusercontent.com/22439051/30163993-47424c34-9405-11e7-922a-6e4984414420.png)

**Comment by payalord** [comment]
Can you please share your xzoom JS initialization code and HTML markup? I'll try to replicate this problem on my end.
