### ISSUE TITLE
Mobile / Tablet device rotation

### ISSUE THREAD

**Issue by psweeting1** [payalord/xZoom#22]
Zooming into images via an Ipad or Iphone works just fine, however if user changes their viewport from portrait to landscape (rotating their device) the zoom container doesn't disappear and fixes itself to the screen unless user some how changes the image in the gallery. Is there a way to prevent this?

**Comment by payalord** [comment]
Didn't check yet, but [orientationchange](http://demos.jquerymobile.com/1.0a2/#docs/api/events.html) event is possible to use to run some corrections with xZoom instance i guess.

**Comment by payalord** [comment]
I'll try to replicate this later on my end here. To see what is possible to do.

**Comment by payalord** [comment]
I didn't check will this code work or not, but you can try this one:
```javascript
var instance = $('.xzoom, .xzoom-gallery').xzoom();

var isTouchSupported = 'ontouchstart' in window;

if (isTouchSupported) {
    //Initial orientation value
    var sco1 = 0;

    $(window).bind("resize", function(){
        //90 = landscape, 0 = portrait
        var sco2 = ($(window).width() > $(window).height())? 90 : 0;
        if(sco1 != sco2) {
            sco1 = sco2;

            //Close zoom because orientation just has been changed
            instance.closezoom();
        }
    });
}
```

**Comment by psweeting1** [comment]
I tried and tested this code, unfortunately it didn't work. No errors in my console.

**Comment by psweeting1** [comment]
I was able to fix the problem using some Javascript instead of jQuery. I couldn't seem to get Jquery mobile orientationchange to work at all, it created more problems than fixed. 

```
window.addEventListener("orientationchange", function() {
                console.log('Change'); //Show the change in the console
                instance.closezoom(); //close the crashed zoom container
            }, false);
```

I added this under my touch condition section.
