### ISSUE TITLE
IE10 Lens glitch

### ISSUE THREAD

**Issue by psweeting1** [payalord/xZoom#25]
![error 1](https://user-images.githubusercontent.com/9356160/30868488-b38e428c-a2d6-11e7-909d-67d615017364.png)

This only happens on IE10 and lower, I'm using Windows 10, IE11 internet browser emulating IE10. This could be an emulation issue as it seems to fine on Windows 7 IE10 (virtual box).

The lens breaks out of image container. The zoomed image is also reversed in it's controls, so you have to scroll zoom backwards to see the zoomed image, which seems to be the lower res image not the high res image. 

I don't think this is a CSS issue from what I can tell.

If you could help or shine some light on the problem, I would be very grateful.

**Comment by payalord** [comment]
Possible, that this can be: [IE not rendering CSS properly when the site is located at networkdrive](https://stackoverflow.com/questions/4966952/ie-not-rendering-css-properly-when-the-site-is-located-at-networkdrive), but I'm not sure. I have faced long time ago the problem with IE 9 not rendering page correctly, while on production server which i accessed via Internet, everything was just fine.

P.S. IE was always pain in the ***

**Comment by psweeting1** [comment]
I'm going to put this down to IE11 rendering wrong in emulation, because I really can't replicate it through IE10 Virtual box and Edge emulation. 

IE is just the worst.

Thanks for your help and advice as always!
