### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by AlbinCauderlier** [payalord/xZoom#28]
XZoom would be awesome if we could ad a keyboard navigation with -> and <-

@payalord XZoom is a really great library that I will use for an e-commerce website.
Feel free publishing (or sending me albin.cauderlier@gmail.com) your bitcoin address for a donation.

**Comment by payalord** [comment]
Hi, thank you. Here is my bitcoin address: 13PqcnMSY5k7LJhyaMa4gS1Jj11SLGaq9V
Good idea to create some public donation button for bitcoin. Will make it later.

With xZoom API and some little jQuery code you can try next approach to implement navigation with -> and <- arrow keys:
```javascript
// Getting an instance
var xzoom = $('.xzoom, .xzoom-gallery').xzoom();

$("body").keydown(function(e) {
    var index = xzoom.gallery().index;
    var max = xzoom.gallery().ogallery.length - 1;

    if(e.keyCode == 37) {
        // left pressed
        index--;
        if (index < 0) index = max;
        $('.xzoom-gallery').eq(index).trigger('click');
    } else if(e.keyCode == 39) {
        // right pressed
        index++;
        if (index > max) index = 0;
        $('.xzoom-gallery').eq(index).trigger('click');
    }
});
```

**Comment by AlbinCauderlier** [comment]
Thank you!
I can't use xZoom for now because de jQuery version seems to be not compliante with some other library.

Have you schedule to upgrade soon?

**Comment by payalord** [comment]
Which jQuery version you need xZoom to work with? I will test and make sure that xZoom supports all jQuery versions from 1.2.6+

**Comment by AlbinCauderlier** [comment]
Works fine! Thanks!
I use JQuery 3.2.1.
I made the integration and got a very small zoom. Next steps by e-mail.

**Comment by AlbinCauderlier** [comment]
I have got 3 small issues (5px offset, moving slow, position of the thumb, ...).
I tried many improvements, without success (CSS modification of 5px, more JS libraries, ...)
