### ISSUE TITLE
Put the "transparent blue" as a JSON parameter

### ISSUE THREAD

**Issue by AlbinCauderlier** [payalord/xZoom#29]
When the mouse hovers the image, there is a "transparent blue" on the picture.
I will change it for my own brand for a green, but I suppose I will be not the only one changing it.

**Comment by payalord** [comment]
You have an option to change tint color behind the lens via `tint` option. And transparency via `tintOpacity` option. Please check the [manual](https://github.com/payalord/xZoom/blob/master/doc/manual.md#options) for the full list of options.

For more deep control of the styles you can change CSS styles of xZoom classes in `xzoom.css` file.
