### ISSUE TITLE
issue about all images

### ISSUE THREAD

**Issue by Avinash-12345** [payalord/xZoom#30]
Hi sir,
How can apply for all images..

**Comment by payalord** [comment]
Please check the [xZoom Sandbox](https://github.com/payalord/xzoom-sandbox) there is examples of how to proper initialize xZoom Plugin. Usually people using Initialization like in 2nd example it was demonstrated.

And also i have created [youtube videos](https://www.youtube.com/watch?v=yUA6O1w-AyE&list=PLg7jElINXnDiDNzq02uAHZy0thDe5pvxm&index=2) where you can see how i have done this.
