### ISSUE TITLE
Zoom for each product

### ISSUE THREAD

**Issue by Miloti** [payalord/xZoom#32]
Hello!
Is it possible to show img class="xzoom" multiple times?
Here, I want to zoom each products something like this:
img class="xzoom" src="1.jpg" xoriginal="gallery/original/1.jpg"
img class="xzoom" src="2.jpg" xoriginal="gallery/original/2.jpg"
img class="xzoom" src="3.jpg" xoriginal="gallery/original/3jpg"
img class="xzoom" src="4.jpg" xoriginal="gallery/original/4.jpg"

The problem is that I can only zoom the first product image, other products images keep frozen (no zoom or anything)!
Mabybe do I need to write some javascript or some ID for each xzoom class? Please help,

Thanks :)

**Comment by payalord** [comment]
Are you trying to show multiple zooms on one page per each image? If yes, then in this case you need to run xzoom initialization per each image separately. Example:

```html
<img class="xzoom" src="1.jpg" xoriginal="gallery/original/1.jpg" />
<img class="xzoom" src="2.jpg" xoriginal="gallery/original/2.jpg" />
<img class="xzoom" src="3.jpg" xoriginal="gallery/original/3.jpg" />
<img class="xzoom" src="4.jpg" xoriginal="gallery/original/4.jpg" />
```

```javascript
$('.xzoom').each(function() {
    $(this).xzoom(); //<-- Don't forget to add your options here
});
```

**Comment by Miloti** [comment]
Hi,

Thanks for your answer :)

I'm new to Javascript. I'm trying to show **one section here:**

 `<section id="default" class="padding-top0">
    <div class="row">
      <div class="large-12 column"><h3>Section1</h3></div>
      <div class="large-5 column">
        <div class="xzoom-container">
          <img class="xzoom" id="xzoom-default" src="1.jpg" xoriginal="images/original/1.jpg" />
          <div class="xzoom-thumbs">
            <a href="1.jpg"><img class="xzoom-gallery" width="80" src="1.jpg"  xpreview="1.jpg" title="The description goes here"></a>
            <a href="2.jpg"><img class="xzoom-gallery" width="80" src="2.jpg" title="The description goes here"></a>
            <a href="3.jpg"><img class="xzoom-gallery" width="80" src="3.jpg" title="The description goes here"></a>
            <a href="4.jpg"><img class="xzoom-gallery" width="80" src="4.jpg" title="The description goes here"></a>
          </div>
        </div>        
      </div>
      <div class="large-7 column"></div>
    </div>
    </section>`

**One here:** (with same xzoom class name)
`<section id="default" class="padding-top0">
    <div class="row">
      <div class="large-12 column"><h3>Default options</h3></div>
      <div class="large-5 column">
        <div class="xzoom-container">
          <img class="xzoom" id="xzoom-default" src="1.jpg" xoriginal="images/original/1.jpg" />
          <div class="xzoom-thumbs">
            <a href="1.jpg"><img class="xzoom-gallery" width="80" src="1.jpg"  xpreview="1.jpg" title="The description goes here"></a>
            <a href="2.jpg"><img class="xzoom-gallery" width="80" src="2.jpg" title="The description goes here"></a>
            <a href="3.jpg"><img class="xzoom-gallery" width="80" src="3.jpg" title="The description goes here"></a>
            <a href="4.jpg"><img class="xzoom-gallery" width="80" src="4.jpg" title="The description goes here"></a>
          </div>
        </div>        
      </div>
      <div class="large-7 column"></div>
    </div>
    </section>`

**and so on for each product row** from my database rows (I have skipped the php part here for simplifying the problem). 
However it seems to work only for the first product section, the rest sections keep frozen while hovering over the image.

**Comment by payalord** [comment]
So it would be 2 sections with 2 zooms per 1 product?

**Comment by Miloti** [comment]
I think there would be 2 or infinite sections, each of them with the same xzoom properties.

**Comment by payalord** [comment]
Ok, give me couple minutes. I'll show you the solution :)

**Comment by Miloti** [comment]
I'm new to Javascript and I have been searching for this for long but no results so far 
Thanks :)

**Comment by payalord** [comment]
Ok, let's say 1 section we will use per 1 product in this case, example with 2 sections(2 products):

```html
<section id="default" class="padding-top0">
	<div class="row">
		<div class="large-12 column">
			<h3>Section1</h3>
		</div>
		<div class="large-5 column">
			<div class="xzoom-container">
				<img class="xzoom" id="xzoom-default" src="1.jpg" xoriginal="images/original/1.jpg" />
				<div class="xzoom-thumbs">
					<a href="1.jpg"><img class="xzoom-gallery" width="80" src="1.jpg" xpreview="1.jpg" title="The description goes here"></a>
					<a href="2.jpg"><img class="xzoom-gallery" width="80" src="2.jpg" title="The description goes here"></a>
					<a href="3.jpg"><img class="xzoom-gallery" width="80" src="3.jpg" title="The description goes here"></a>
					<a href="4.jpg"><img class="xzoom-gallery" width="80" src="4.jpg" title="The description goes here"></a>
				</div>
			</div>
		</div>
		<div class="large-7 column"></div>
	</div>
</section>

<section id="default" class="padding-top0">
	<div class="row">
		<div class="large-12 column">
			<h3>Default options</h3>
		</div>
		<div class="large-5 column">
			<div class="xzoom-container">
				<img class="xzoom" id="xzoom-default" src="1.jpg" xoriginal="images/original/1.jpg" />
				<div class="xzoom-thumbs">
					<a href="1.jpg"><img class="xzoom-gallery" width="80" src="1.jpg" xpreview="1.jpg" title="The description goes here"></a>
					<a href="2.jpg"><img class="xzoom-gallery" width="80" src="2.jpg" title="The description goes here"></a>
					<a href="3.jpg"><img class="xzoom-gallery" width="80" src="3.jpg" title="The description goes here"></a>
					<a href="4.jpg"><img class="xzoom-gallery" width="80" src="4.jpg" title="The description goes here"></a>
				</div>
			</div>
		</div>
		<div class="large-7 column"></div>
	</div>
</section>
```
Then your initialization script must be like this:
```javascript
$('.xzoom').each(function() {
	var instance = $(this).xzoom(); //<-- Don't forget to add your options here
	$('.xzoom-gallery', $(this).parent()).each(function () {
		instance.xappend($(this));
	});
});
```

**Comment by Miloti** [comment]
Still the same issue :( can't zoom the second section.

**Comment by payalord** [comment]
I can show you working example with 4 sections on one page? If you wish. So you can examine the example. And check the difference with your page then.

**Comment by Miloti** [comment]
Yes sure, I would be very happy to see a working example :)

**Comment by payalord** [comment]
Here we go, check this example: https://github.com/payalord/xzoom-sandbox/tree/master/InitializationMultipleZooms

**Comment by Miloti** [comment]
It works :) 
This is exactly what I was looking for. Thank you very much for your help.

**Comment by payalord** [comment]
Nice, you are welcome!
