### ISSUE TITLE
Navigation without thumbnail

### ISSUE THREAD

**Issue by samiromar** [payalord/xZoom#33]
Is it possible to have next and previous navigation buttons without displaying the thumbnails?

**Comment by payalord** [comment]
Yes, I think it is possible to do a custom workaround for this via xZoom API to accomplish this. But if there is no thumbnails. Then the question is where you will store information of the pictures? In javascript array or object? Or somewhere in html img tags but hidden?

**Comment by samiromar** [comment]
Thumbnails are specified using div, but i will hide the div by just adding "display: none" in the "xzoom-thumbs" style. What i need is a next and previous button to the left and right of preview image.
```

 <div class="xzoom-thumbs">
<!-- Image list -->
</div>
```

```
.xzoom-thumbs {
    display: none;
    text-align: center;
    margin-bottom: 10px;
    margin-top: 50px;
}
```

**Comment by payalord** [comment]
You can try to use next approach, with loop on:
```javascript
// Getting an instance
var xzoom = $('.xzoom, .xzoom-gallery').xzoom(); //<-- Don't forget to add your options here
var index = xzoom.gallery().index;
var max = xzoom.gallery().ogallery.length - 1;

$('#left').on('click', function() {
    // left clicked
    index--;
    if (index < 0) index = max;
    $('.xzoom-gallery').eq(index).trigger('click');
});
$('#right').on('click', function() {
    // right clicked
    index++;
    if (index > max) index = 0;
    $('.xzoom-gallery').eq(index).trigger('click');
});
```
Or second one, with loop off:
```javascript
// Getting an instance
var xzoom = $('.xzoom, .xzoom-gallery').xzoom(); //<-- Don't forget to add your options here
var index = xzoom.gallery().index;
var max = xzoom.gallery().ogallery.length - 1;

$('#left').on('click', function() {
    // left clicked
    index--;
    if (index < 0) index = 0;
    $('.xzoom-gallery').eq(index).trigger('click');
});
$('#right').on('click', function() {
    // right clicked
    index++;
    if (index > max) index = max;
    $('.xzoom-gallery').eq(index).trigger('click');
});
```

**Comment by payalord** [comment]
Let assume you are using `xzoom-gallery` class for thumb images in image list. Then by clicking on elements with ID `left` and `right` you want switch between those images.

**Comment by payalord** [comment]
And one more thing, I didn't tested this code yet. Just wrote it as is. Please check is it working or not and let me know if you have troubles with it.

**Comment by samiromar** [comment]
Thank you for your quick responses, i will test it and let you know

**Comment by samiromar** [comment]
It worked like a wonder 👍  thank you so much
on a separate note, is there anyway to fit the preview image to the height of container or available space? instead of specifying size in pixel, possible to specify height in percentage?

**Comment by samiromar** [comment]
it will be better if you provide an option to show thumbnails or not, (showThumbnail : true/false)
and may include this as custom Navigation option, just a suggestion

**Comment by payalord** [comment]
We can try next approach - you can setup as a preview your own custom container for example by ID via position option, like this:
```html
<div id="custom_id" style="width:50%; height 50%;"></div>
```
```javascript
$('.xzoom, .xzoom-gallery').xzoom({position: '#custom_id'});
```
where your custom container have a style in css to fit height by percentage or any other script or style logic on how to fit the needed area.

But again I didn't tested this too. Please let me know, does this works for you or not.

**Comment by payalord** [comment]
Good idea about option for showThumbnails. Maybe in next versions I will include it.

**Comment by samiromar** [comment]
the custom container approach didnt work, its applying for the original image not xpreview image. i tried another approach with CSS

```
.xzoom-container {
 height: 100% !important;
}

  .xzoom-container img {
     height: 100% !important;
    cursor: crosshair;
}

this looks ok, let me test further.

```

**Comment by payalord** [comment]
On this weekend, I'll try to make my own example for this issue. And will add it to xzoom-sandbox.

**Comment by payalord** [comment]
I will close this issue, because main topic is solved. If there will be need to fix something else please open a new issue. Thanks.
