### ISSUE TITLE
is it necessary to have all the three folders 

### ISSUE THREAD

**Issue by Abdullah77777** [payalord/xZoom#35]
Hello;

  thank you very much for this great work. I`m trying to implement this code and I faced the issue of having to have originals, previews and thumbs folders. what I wanna do is to have only one folder for the originals. is that possible?  thanks in advance.

**Comment by payalord** [comment]
Yes, i think so. That is possible.

If you will use only original images. For preview and thumbs it will be scaled by the browser.

**Comment by Abdullah77777** [comment]
in my case, the thumbs size I did control using the width and height in the image tag inside the thumbs dive:
<img class="xzoom-gallery" width="68" height="58" ... />
. However, for the perview, I failed to do so, in fact I don't know how to control the size of it. so when I click the thumb I get the full size photo in the preview panel. please advise!

**Comment by payalord** [comment]
I have created example for you with only original images, please check here: https://github.com/payalord/xzoom-sandbox/tree/master/xZoomOnlyOriginal

**Comment by Abdullah77777** [comment]
Thank you so much man,  It is working as it should.
