### ISSUE TITLE
Thumbnail on hover

### ISSUE THREAD

**Issue by Miloti** [payalord/xZoom#36]
New with jQuery and Javascript. I'm trying to implement xzoom-thumbs on hover (rather than thumbs click), similar to this:
For example: [http://52.88.132.26/DB/Artikulli.php?id=341](url)

`$(document).ready(function(){
			$('.xzoom-thumbs img').hover(function() {
			var url = $(this).attr('src');
			$('#xzoom-default').attr('src', url);
		});
		});`

You see while hovering over thumbs, the original image updates to the corresponding thumb item. However, not the xzoom-preview. In this case, in order for xzoom to work properly I have to click in thumbs, which is not what I want.

Neither this didn't work:
`$(document).ready(function(){
				$('.xzoom-thumbs img').on('click hover',function(){
				$('#xpreview').attr('src',$(this).attr('src'));
			});
		});`

Nor this:
`$(document).ready(function(){
			$('.xzoom-thumbs img').hover(function() {
			var url = $(this).attr('src');
			$('#xzoom-default').attr('src', url);
			$('.xzoom-thumbs img').trigger('click');
		});
		});`

Am I missing something in the script?

Thanks.

**Comment by payalord** [comment]
Have you tried to use `hover` option of xZoom?

**Comment by payalord** [comment]
You can find `hover` option description in the list of available options here: https://github.com/payalord/xZoom/blob/master/doc/manual.md#options

**Comment by Miloti** [comment]
No, I didn't try hover option of xZoom. 
Thanks for the link. I'm going to read the description..

**Comment by Miloti** [comment]
This didn't work for me :(
`(function ($) {
    $(document).ready(function() {

        //Initialization with one class name
        $(".xzoom").xzoom();
			hover: true
    });
})(jQuery);`

Maybe I'm missing something?

**Comment by payalord** [comment]
Options are case sensitive. And must be passed to xZoom as javascript object, example:
```javascript
$(".xzoom").xzoom({option1: value, option2: value, ...});
```

So in your case, this is how you need to provide `hover` option to xzoom:
```javascript
(function ($) {
$(document).ready(function() {

    //Initialization with one class name
    $(".xzoom").xzoom({hover: true});

});
})(jQuery);
```

You also can check this example to get better idea of how to work with options: https://github.com/payalord/xzoom-sandbox/tree/master/Options

Feel free to download xZoom Sandbox repository and experiment with examples:
https://github.com/payalord/xzoom-sandbox

**Comment by Miloti** [comment]
Thanks for your solution. 
Your example works fine :) However when using multiple zooms and applying hover at the same time, I'm unable to set the lens color, zoomwidth and zoomheight parameters. Like this:

`(function ($) {
    $(document).ready(function() {
        //Multiple Zooms on one page
        $('.xzoom').each(function() {
            var instance = $(this).xzoom({zoomWidth: 700, zoomHeight: 550, lens: "#ffffff"}); //<-- Don't forget to add your options here
            $('.xzoom-gallery', $(this).parent()).each(function () {
                instance.xappend($(this));
            });
        });
    });
})(jQuery);`

I tried many options inside the `$('.xzoom').xzoom(...)` and `$(".xzoom").xzoom(...)` but still unable to keep the parameters that I want.

**Comment by payalord** [comment]
In your case with multiple zooms on one page, this is how you need to provide your options:
```javascript
(function ($) {
  $(document).ready(function() {

    //Multiple Zooms on one page
    $('.xzoom').each(function() {
      
      var instance = $(this).xzoom({zoomWidth: 700, zoomHeight: 550, lens: "#ffffff", hover: true});
      
      $('.xzoom-gallery', $(this).parent()).each(function () { 
        instance.xappend($(this));
      });
    });
  });
})(jQuery);
```

Also make sure you are using `xzoom` class for main image and `xzoom-gallery` class for thumbs images.

In case if you will still have problems with this. I can create a working example with multiple zooms on one page with hover option for you then.

**Comment by Miloti** [comment]
This:

`(function ($) {
  $(document).ready(function() {

    //Multiple Zooms on one page
    $('.xzoom').each(function() {
      
      var instance = $(this).xzoom({zoomWidth: 700, zoomHeight: 550, lens: "#ffffff", hover: true});
      
      $('.xzoom-gallery', $(this).parent()).each(function () { 
        instance.xappend($(this));
      });
    });
  });
})(jQuery);` 

didn't work.
I use xzoom class for main image and xzoom-gallery for thumbs but it didn't work. 

```
<a href="images/images/gallery/original/<?php echo trim($images[$i]); ?>" >
<img class="xzoom" width="50" src="images/images/gallery/thumbs/<?php echo trim($images[$i]); ?>" xpreview="images/images/gallery/preview/<?php echo trim($images[$i]); ?>" />
</a>	
```

`<a href="images/images/gallery/original/<?php echo trim($images[$i]); ?>">
<img class="xzoom-gallery" width="50" src="images/images/gallery/preview/<?php echo trim($images[$i]); ?>" title=""></a>`

I'm testing more, I would be happy to see a working example :)

**Comment by payalord** [comment]
Please download and check this example in the browser: https://github.com/payalord/xzoom-sandbox/tree/master/InitializationMultipleZoomsOptions

**Comment by Miloti** [comment]
This works 👍  

Thanks man, this software is amazing :)

**Comment by payalord** [comment]
You welcome!
