### ISSUE TITLE
xzoom is not a function

### ISSUE THREAD

**Issue by aneeskodappana** [payalord/xZoom#37]
when i import this plugin into an angular project using the following syntax
```
import 'xzoom';

```

the console showing xzoom is not a function.

any idea to use xzoom in an angular project.
Is this plugin ok to use with webpack?

Thank you

**Comment by payalord** [comment]
xZoom is jQuery plugin. And not ready out of the box to be imported in projects by webpack. But you can try to use one of the suggested approach to first get jQuery into your globals, and then same way load xZoom: https://stackoverflow.com/questions/28969861/managing-jquery-plugin-dependency-in-webpack

**Comment by payalord** [comment]
Anyway this is good question, I'll try to make working example later in https://github.com/payalord/xzoom-sandbox

**Comment by payalord** [comment]
please use `require` instead of `import` after you properly loaded jQuery, this must fix import problem.
