### ISSUE TITLE
Mouse Scroll Zooming - Configurable Rate

### ISSUE THREAD

**Issue by poebrand** [payalord/xZoom#38]
Currently the mouse scroll zoom is hard-coded at 5%. Can you make that a configurable value per instance? 

Thanks!

**Comment by payalord** [comment]
Yeah, this is good idea. I will do this in couple days. As a new release version.

**Comment by poebrand** [comment]
Thanks!

**Comment by payalord** [comment]
I'm checking the code and just noticed. That I had implemented the possibility to control scale delta (that 5%) manually even by current version via `event.xscale`. Here is example:
```javascript
var instance = $('.xzoom, .xzoom-gallery').xzoom();

var scale = 0;
var scaleDelta = 0.05; //Setup your delta here

instance.eventscroll = function(element) {
    element.xon('mousewheel DOMMouseScroll', function(event){
        var delta = -event.originalEvent.detail || event.originalEvent.wheelDelta || event.xdelta;
        if (delta > 0) delta = -scaleDelta; else delta = scaleDelta;
        scale += delta;
        if (scale < -1) scale = -1;
        if (scale > 1) scale = 1;
        event.xscale = scale;
        instance.xscroll(event)
    });
}
```

**Comment by payalord** [comment]
But anyway new upcoming release will have this as an easy options.

**Comment by poebrand** [comment]
Sounds good, thank you.

**Comment by payalord** [comment]
To track work progress, please check here: https://github.com/payalord/xZoom/projects/1
