### ISSUE TITLE
Cannot read property 'pageX' of undefined

### ISSUE THREAD

**Issue by anandchapter247** [payalord/xZoom#39]
Hello,

I am trying to use closezoom and openzoom to enable and disable zoomer. But it's returning error `Cannot read property 'pageX' of undefined`

**Comment by payalord** [comment]
Can you show me your javascript code part? So I can analyze where exactly and how you calling closezoom and openzoom. Thanks.

**Comment by anandchapter247** [comment]
Hello @payalord ,

Thank you for your response. Here is the code I'm trying.
// To Close zoom
```
$('body').find('img.xzoom').each(function() {
                var xzoom = $(this).data('xzoom');
                if (xzoom) {
                	xzoom.closezoom();
                }
            });
// To Open Zoom Again:
$('body').find(".tetsId").each(function(index) {
        	var zoom = $(this).data('xzoom');
        	if (zoom) {
        		zoom.openzoom();
        	}else{
        		$(this).xzoom({ position: 'lens', lensShape: 'circle', zoomWidth: '500', zoomHeight: '500' });
                        $(this).trigger('mouseenter');
        	}
        });
```

Here as I've dig out I found that openzoom needed event, But here how can I pass a event as there is no event is triggered.

I want to cloeszoom and openzoom on click of a button.

**Comment by anandchapter247** [comment]
[xZoomCloseIssue.zip](https://github.com/payalord/xZoom/files/1859039/xZoomCloseIssue.zip)

You can Find what I tried, I make some changes in your sandbox code but still there is issue. Can you have a look into this?

**Comment by payalord** [comment]
The reason why `openzoom` need variable `event` is because in the `event.pageX` and `event.pageY` stored current mouse position coordinates. Which is used as start position for the lens when zoom is opening.

**Comment by payalord** [comment]
So the question is, how exactly you planning User Interaction with xZoom? You can even setup by yourself custom `event` variable, like this:
```javascript
var event = {
    pageX = 0, //<-- any custom value you want
    pageY = 0
}
```
Before providing it to `openzoom`.

**Comment by anandchapter247** [comment]
I've tried to close zoom on click of a button but it doesn't close zoom, while in sandbox code, it closes the zoom but when I add a button in the same code to close zoom it doesn't work means not closing zoom. I've added a sample code in my last comment. Please have a look into this, and help me out.

**Comment by payalord** [comment]
I checked your code. There is a problem with mouse coordinates. The requirement for zoom to work is that operating mouse position/area(coordinates) must be on the image that must be zoomed. That is the logic implemented natively. But it can be customized.

For example - on mobile devices(touch devices) there is no such thing like mouse at all. But operating position we can get from touch gestures. And requirement is still the same - it must be inside area of the image. Only in case of fullscreen the whole screen is operating area.

But with your example button which opens zoom is far away from image and not inside of operating area. So when zoom is opened by button it then immediately closed on first mouse move, Because mouse position is outside of zoom borders(operating area).

So I need more clearly understand first what exactly you are trying to achieve with buttons. To be able to help you better.

**Comment by anandchapter247** [comment]
![images](https://user-images.githubusercontent.com/8499364/38184623-89f8dfa8-3666-11e8-91eb-71ae3ba72387.png)
I've attached screenshot for what I'm trying to achieve. Please have a look and let me know.

**Comment by payalord** [comment]
Ok, please check this example: https://github.com/payalord/xzoom-sandbox/tree/master/OpenWithButton

**Comment by anandchapter247** [comment]
@payalord  thank you.
It worked, I'm closing this as my problem is solved.

**Comment by anandchapter247** [comment]
Hello @payalord , I've fix last issue but I've other point that is, how can I set min and max size of zoom lense? I want that user can only zoom at some point and after that zoom should not work and same for max size.

**Comment by payalord** [comment]
Please read my comment here about lens size: https://github.com/payalord/xZoom/issues/42

Currently in couple of other issues we discussing the possible options on how to extended scale functionality and things that connected to it. Like **lens** for example. So I planning very soon to release new version of xZoom where I will add options to have more deep control for things like lens min, max, scale props and much other stuff. Probably this will be at this weekend.

**Comment by anandchapter247** [comment]
Please let me know once it's ready.

**Comment by payalord** [comment]
Ok, no problem.

**Comment by anandchapter247** [comment]
@payalord any update ?

**Comment by payalord** [comment]
In progress.

**Comment by anandchapter247** [comment]
Thank you.. waiting for next release. hope will get it asap.

**Comment by payalord** [comment]
I have created boards, so it will be possible to track of what am I working on currently. Please check them here (Projects tab): https://github.com/payalord/xZoom/projects/1

Sorry for the delay, but it takes time. And I'm working on my free time on this.
