### ISSUE TITLE
Different sizes of additional images breaks down zoom proportions

### ISSUE THREAD

**Issue by payalord** [payalord/xZoom#4]
After first zoom initialization(first opening of zoom) somehow it is saved first image sizes and they used after that to calculate proportions for zoom other images if we switch to them. This breaks down proportions of image and lens size on output.

Need to fix this by reset old saved image sizes on opening new image in the zoom if we switch to next image.

**Comment by Whip** [comment]
This is the best zoom plugin I've found so far and yes this bug is annoying. I hope you'll find time to improve this. I tried reading it several times but the complexity is beyond my ability.

**Comment by payalord** [comment]
I think i fixed it, but still need little more testing. If you wish you can help test it, by downloading min version from dev branch here: https://raw.githubusercontent.com/payalord/xZoom/dev/dist/xzoom.min.js

**Comment by payalord** [comment]
I have tested and made new release v1.0.5, i think it's good now.
