### ISSUE TITLE
Examples: mouse over not working in Chrome and FireFox on Windows 10

### ISSUE THREAD

**Issue by poebrand** [payalord/xZoom#41]
On the examples... the mouse over behavior that opens zoom is not working in Chrome 65.0.3325.181 and FireFox 59.0.2 on Windows 10 desktop (multiple computers). It was working yesterday. I double-checked that it still occurs after clearing cache and opening in incognito mode.

URLs with issue:

- https://payalord.github.io/xZoom/
- https://payalord.github.io/xZoom/examples/index.html

Working in:

- IE 11
- Edge

**Comment by poebrand** [comment]
Upon further investigation, Chrome and FireFox are passing the touch device check in setup.js. IE 11 is not. This appears to be the issue.

`var isTouchSupported = 'ontouchstart' in window;`

![image](https://user-images.githubusercontent.com/737504/38115275-4521c826-3360-11e8-8a38-84cf04765497.png)

**Comment by payalord** [comment]
Thank you, for this analyze and help. Yeah this is how i checked does the touch gesture is supported or not. I think i better to change it to some kind of better or cross platform detection solution, maybe something like this: https://stackoverflow.com/questions/4817029/whats-the-best-way-to-detect-a-touch-screen-device-using-javascript
