### ISSUE TITLE
Lens size

### ISSUE THREAD

**Issue by bdolleschal** [payalord/xZoom#42]
Hi, I was looking for an option which let me set the size of the lens. Can you help me with that? Thank you!

**Comment by payalord** [comment]
If make this simple, then I can tell that - lens size depends on scale value and shows what part of image is zoomed/scaled in preview.

To control this on opening, you have an option `defaultScale` for now. I think all of this stuff with scale need to be extended to have more control options. But this will come in future releases soon.

**Comment by bdolleschal** [comment]
no matter what value I am using for defaultScale there is no change in the result

```    $('.xzoom').each(function() {
		$(this).xzoom({
			zoomWidth:250,
			zoomHeight:250,
			lensCollision:false,
			defaultScale:-1,
			smoothScale:6,
			smoothZoomMove:6
		});
	});
```

**Comment by payalord** [comment]
I have created a working example for you in xzoom-sandbox. Please check it here: https://github.com/payalord/xzoom-sandbox/tree/master/DefaultScale
It shows that lens size is possible to change by default scale in range -100% to +100%.
