### ISSUE TITLE
Can i use original image for thumbnail and for the preview?

### ISSUE THREAD

**Issue by vnxx** [payalord/xZoom#46]
$('.xzoom').css('width','350px');

i use that code for resize the default width of the image because i don't want use many image, but i got a problem when i click the thumbnail for change the preview when i do that width of the preview became normal not 350px.

**Comment by payalord** [comment]
Yes you can. But if you use only original images for everything then you need setup image widths for main image and thumbnails (img tag width property). Please check this example: https://github.com/payalord/xzoom-sandbox/blob/master/OnlyOriginal/index.html

**Comment by vnxx** [comment]
thank you, it's working
