### ISSUE TITLE
Is it a must to put the thumbs after the xzoom

### ISSUE THREAD

**Issue by wisamx** [payalord/xZoom#47]
I have put the xzoom-thumbs first.
then I put the main xzoom image
but the script zooms on the first thumb! rather the xzoom main image

**Comment by payalord** [comment]
No, it is not a must. That's a bug, that I need to fix. But for now you can use next workaround:
```javascript
var instance = $('.xzoom').xzoom(); //<-- your options here
$('.xzoom-gallery').each(function(){
    instance.xappend($(this));
});
```
https://github.com/payalord/xzoom-sandbox/tree/master/ThumbsFirst

**Comment by MacchiFilippo** [comment]
Yes it works but:

1- the browser console gives an error on loading script: TypeError: c is undefined
2- the customization of the zoom layer doesn't work anymore

`var xzoom = $("#xzoom-default, .xzoom-gallery").xzoom({ zoomWidth: 530, zoomHeight: 450, title: false, tint: '#333', Xoffset: 15, bg: '#fff' });
        var isTouchSupported = 'ontouchstart' in window;

        if (isTouchSupported) {
            xzoom.eventunbind();
            var mc1 = new Hammer($('#xzoom-default')[0]);

            mc1.on("tap", function (event) {
                event.pageX = event.srcEvent.pageX;
                event.pageY = event.srcEvent.pageY;

                xzoom.eventclick = function (element) {
                    element.css('touch-action', 'pan-x');
                };

                xzoom.eventmove = function (element) {
                    var mc2 = new Hammer(element[0]);

                    mc2.get('pan').set({ direction: Hammer.DIRECTION_ALL });

                    mc2.on('pan', function (event) {
                        event.pageX = event.srcEvent.pageX;
                        event.pageY = event.srcEvent.pageY;
                        xzoom.movezoom(event);                        
                    });
                };

                xzoom.eventleave = function (element) {
                    var mc3 = new Hammer(element[0]);
                    mc3.on('tap', function (event) {
                        xzoom.closezoom();
                    });
                };
                xzoom.openzoom(event);
            });
        } else {
            $('#xzoom-default').bind('click', function(event) {
                var xzoom = $(this).data('xzoom');
                xzoom.closezoom();
                var gallery = xzoom.gallery().cgallery;
                var i, images = new Array();
                for (i in gallery) {
                    images[i] = {src: gallery[i]};
                }
                $.magnificPopup.open({items: images, type:'image', gallery: {enabled: false}});
                event.preventDefault();
            });
        }`

**Comment by payalord** [comment]
@MacchiFilippo sorry I don't see any `instance.xappend` in your code. Are you trying to use **thumbs first** solution along with **hammer.js** and **magnific popup**?

**Comment by MacchiFilippo** [comment]
@payalord yes it's right

**Comment by payalord** [comment]
@MacchiFilippo ok then today later I'll create an example for it in sandbox.

**Comment by MacchiFilippo** [comment]
@payalord thank you

**Comment by payalord** [comment]
Here source of example [ThumbsFirstHammerMagnific](https://github.com/payalord/xzoom-sandbox/tree/master/ThumbsFirstHammerMagnific) and here you can check it online from mobile device https://payalord.github.io/xzoom-sandbox/ThumbsFirstHammerMagnific/

**Comment by MacchiFilippo** [comment]
It works thank you very much!
