### ISSUE TITLE
Position: 'lens' not working...

### ISSUE THREAD

**Issue by Budapresst** [payalord/xZoom#48]
I can't get Position: 'lens' to work.  I thought it was me, so I checked out your "Lens options" demo here: https://payalord.github.io/xZoom/ and it doesn't work (for me) on your site either.  I've tried the latest versions of FF and Chrome on Win10.  Please advise.

**Comment by payalord** [comment]
Thanks for reporting this issue. Probably patching other issues caused this side effect. And this is bug. I will fix it today.

**Comment by Budapresst** [comment]
awesome!  thanks!

**Comment by payalord** [comment]
Ok, i made a new patch release. Please check now.

**Comment by Budapresst** [comment]
Working!  Thanks, man!  :)
