### ISSUE TITLE
Multiple Galleries

### ISSUE THREAD

**Issue by Budapresst** [payalord/xZoom#49]
Could you point me in the right direction?

I want to have multiple galleries per product and load them based on the value change of a select dropdown.  I was thinking of just loading up 3 instances of xZoom, hiding two of them with CSS, and then changing the value CSS display value according as the user interacts with the select dropdown.  

What would you recommend in terms of a strategy with your plugin?

**Comment by payalord** [comment]
I don't think here you need specific strategy, but whatever works better for you. If hiding will not cause any troubles and after you show xZoom it will work. Then i it's ok to use it like that with no problem.

But it is possible if needed to reinitialize xZoom in case if it has been broken by deleting the DOM etc.

And one more thing, have you looking xzoom sandbox? It has more examples: https://github.com/payalord/xzoom-sandbox
Maybe some of them will be useful for you.

**Comment by Budapresst** [comment]
thank you!  i'll check the sandbox and do some experimenting... :)
