### ISSUE TITLE
Embed videos instead of images

### ISSUE THREAD

**Issue by cristobalocampo** [payalord/xZoom#51]
Hey! I'm using the plugin and checking the showcases and I was wondering if it's possible to **embed videos**, example using a plain icon thumbnail and instead of opening the preview/zoom it should display a videos in a default HTML player. I don't if it's possible but I was wondering if you had thought in something similar while creating this. Any comment is appreciated, thank you and great work here!

**Comment by payalord** [comment]
Please check this issue: [Videos / Iframe #17](https://github.com/payalord/xZoom/issues/17) it might be something similar. But if that doesn't work for you and you have specific requirements. I can try to find a workaround solution for your case.

**Comment by cristobalocampo** [comment]
Hey! that's perfect...for an iframe haha, my use case was a lot simpler and I managed to get away just addding a "thumbnail" and using another plugin to open a popup with a plain HTML `<video>` I will close this now. Thank you, and again, great plugin!
