### ISSUE TITLE
This plugin is compatible with jQuery.min v3.3.1 ??

### ISSUE THREAD

**Issue by RefrelSL** [payalord/xZoom#56]
I do what the tutorial says but it still does not work in HTML

**Comment by payalord** [comment]
I just tested it, works fine for me. You can try test it with https://github.com/payalord/xzoom-sandbox examples, take any example and change jQuery version to 3.3.1, then open that html example in the browser. And btw which browser you are testing with?

**Comment by payalord** [comment]
Working example here:
https://payalord.github.io/xzoom-sandbox/jQuery/3.3.1/

Source code:
https://github.com/payalord/xzoom-sandbox/tree/master/jQuery/3.3.1

**Comment by RefrelSL** [comment]
Thanks!
