### ISSUE TITLE
there is a dependency with foundation js?

### ISSUE THREAD

**Issue by pabloyokese** [payalord/xZoom#57]
I am using bootstrap 4 and I realized when I open the component in a mobile device the main picture get bigger after click in the thumbs , but after adding foundation js got fixed the layout issue but the zoom does not work idea idea how to solve this issue ?

**Comment by payalord** [comment]
Sometimes third part styles can affect the behavior of how xZoom working. And probably foundation js removes properly and applies on the moment when needed those styles. Hard to tell without knowing which versions are this with xZoom, jQuery, Foundation. Or if you can reproduce it in https://jsfiddle.net/ i can check it.
