### ISSUE TITLE
Please Update this to work with JQuery v3.1 or later.

### ISSUE THREAD

**Issue by ayoubkhan558-zz** [payalord/xZoom#58]
This plugin works fine with JQuery 2.0. but does not work twith JQuery 3.0 or later.
Please Update this with JQuery v3.1.1.

**Comment by payalord** [comment]
Working example here:
https://payalord.github.io/xzoom-sandbox/jQuery/3.1.1/

Source code:
https://github.com/payalord/xzoom-sandbox/tree/master/jQuery/3.1.1

**Comment by ayoubkhan558-zz** [comment]
Thank You.
