### ISSUE TITLE
While i'm click the first time small preview it the there is that possible to hide this in mobile devices.

### ISSUE THREAD

**Issue by upendraalwafaa** [payalord/xZoom#59]
![Capture - 1](https://user-images.githubusercontent.com/32842147/59156542-2d45c300-8aae-11e9-9a8d-4d3b54651388.PNG)

**Comment by payalord** [comment]
Do you mean to remove open zoom action on tap in mobile devices?

**Comment by upendraalwafaa** [comment]
> Do you mean to remove open zoom action on tap in mobile devices?

Yes

**Comment by payalord** [comment]
You can check is touch gestures supported first and then unbind xzoom events, so no open xzoom action will happen on mobile device on tap:
```javascript
        // Your Initialization code here
        var xzoom = $('.xzoom, .xzoom-gallery').xzoom(); // <-- your options here

        // Checking is touch gestures supported
        var isTouchSupported = 'ontouchstart' in window;
        if (isTouchSupported) {
            // Unbind all xzoom events
            xzoom.eventunbind();
        }
```
