### ISSUE TITLE
xZoom Lens is not adjusting in small size of image

### ISSUE THREAD

**Issue by Abhijeet02** [payalord/xZoom#60]
Hi,
I've used plugin for ecommerce website. I've image size of 500*500. But lens is not adjusting on image. It is taking full width and height on image. 

Please help me.
![xZoom-lens](https://user-images.githubusercontent.com/12933860/59189801-b76a5600-8b98-11e9-94f6-6fb58d27ef4b.png)

**Comment by payalord** [comment]
Hi, can you show me your initialization code? And does your original image higher than preview image by size?

**Comment by Abhijeet02** [comment]
Hi,
I am attaching initialization code.
`$('.xzoom4, .xzoom-gallery4').xzoom({Xoffset: 15, defaultScale: 1, fadeIn: true, adaptive: true});

        //Integration with hammer.js
        var isTouchSupported = 'ontouchstart' in window;

        if (isTouchSupported) {
            //If touch device
            $('.xzoom-gallery').each(function(){
                var xzoom = $(this).data('xzoom');
                xzoom.eventunbind();
            });

        $('.xzoom4').each(function() {

            var xzoom = $(this).data('xzoom');
            $(this).hammer().on("tap", function(event) {
                event.pageX = event.gesture.center.pageX;
                event.pageY = event.gesture.center.pageY;
                var s = 1, ls;

                xzoom.eventmove = function(element) {
                    element.hammer().on('drag', function(event) {
                        event.pageX = event.gesture.center.pageX;
                        event.pageY = event.gesture.center.pageY;
                       // xzoom.movezoom(event);
                        event.gesture.preventDefault();
                    });
                }

                var counter = 0;
                xzoom.eventclick = function(element) {

                    element.hammer().on('tap', function() {
                        counter++;
                        if (counter == 1) setTimeout(openfancy,300);
                        event.gesture.preventDefault();
                    });
                }

                function openfancy() {

                    if (counter == 2) {
                        xzoom.closezoom();
                        $.fancybox.open(xzoom.gallery().cgallery);
                    } else {
                        xzoom.closezoom();
                    }
                    counter = 0;
                }
            xzoom.openzoom(event);
            });
        });

        } else {
            //If not touch device

            //Integration with fancybox plugin
            $('#xzoom-fancy').bind('click', function(event) {
                var xzoom = $(this).data('xzoom');
                xzoom.closezoom();
                $.fancybox.open(xzoom.gallery().cgallery, {padding: 0, helpers: {overlay: {locked: false}}});
                event.preventDefault();
            });
        }
    });`

Original image and preview image are in same size, as we're uploading only one image from backend.

**Comment by payalord** [comment]
Please check xzoom-sandbox example [OnlyOriginal](https://github.com/payalord/xzoom-sandbox/tree/master/OnlyOriginal), you can also check how it works online from your browser on PC device by this link: https://payalord.github.io/xzoom-sandbox/OnlyOriginal/

This example shows how with only original image for both and preview and as original source image xzoom works.

If you will need this example solution mixed with hammer.js and fancybox. Let me know I can combine new mixed example js code in xzoom-sandbox for you.

**Comment by Abhijeet02** [comment]
Hi,
I've seen this example before. There are different image for original, thumb and preview.

Is it any solution to adjust width and height of lens dynamically on image size? 
It would be great if Iens works well on size of 500*500 image size.

**Comment by payalord** [comment]
In that example actually it is used same only original images for everything:
```html
<div style="border:1px solid #ccc; display:inline-block; line-height:0;">
    <img class="xzoom" width="400" src="gallery/original/01_b_car.jpg" xoriginal="gallery/original/01_b_car.jpg" />
</div>
        
<div style="margin-top:10px">
    <a href="gallery/original/01_b_car.jpg" style="display: inline-block;">
        <img class="xzoom-gallery" width="68" src="gallery/original/01_b_car.jpg" />
    </a>

    <a href="gallery/original/02_o_car.jpg" style="display: inline-block;">
        <img class="xzoom-gallery" width="68" src="gallery/original/02_o_car.jpg" />
    </a>

    <a href="gallery/original/03_r_car.jpg" style="display: inline-block;">
        <img class="xzoom-gallery" width="68" src="gallery/original/03_r_car.jpg" />
    </a>

    <a href="gallery/original/04_g_car.jpg" style="display: inline-block;">
        <img class="xzoom-gallery" width="68" src="gallery/original/04_g_car.jpg" />
    </a>
</div>
```

Other than that the only options you have to control width and height of lens are `zoomWidth` and `zoomHeight`, while to control initial scale you can use `defaultScale`.

Maybe would be easier to illustrate me the problem is to reproduce it on https://jsfiddle.net/ so I'll be able to analyze better, what exactly causing the problem. Because as I know xzoom works well with any image sizes.

**Comment by Abhijeet02** [comment]
Sure. I am sending link of js fiddle.

https://jsfiddle.net/Abhijeet02/97jru0zL/

**Comment by payalord** [comment]
Thanks. As i can see in fiddle. Width size for preview is set to 400px in html. While image size is 500 and lens adjusting accordingly by proportions: https://ibb.co/1LPyphZ

**Comment by Abhijeet02** [comment]
Thanks. I've used image width as 100%. so in small size of image lens is not working. It works only if I upload image in high resolution like 1024px. you can check in jsfiddle by removing width of img or set it to 100%.

**Comment by payalord** [comment]
Sorry, wasn't been able to respond in time. Is this issue is still exists?
