### ISSUE TITLE
xZoom lens in mobile

### ISSUE THREAD

**Issue by AnaGonzales** [payalord/xZoom#61]
I'm viewing the example using the lens on an iPhone 7. If you move the lens, you end up scrolling up/down and the lens disappears. You have to be very careful when moving the lens so it actually moves, does not disappear and does not scroll. Anyone else having the same issue? and is there a way to fix that?
on an android phone (Samsung Galaxy), it's behaving exactly as I wanted.

**Comment by payalord** [comment]
Example where zoom inside the lens (with circle or box shape)?

**Comment by AnaGonzales** [comment]
yes, I've been viewing the example with the lens options (circle or box shape) on an iPhone 7. quite fiddly to use on an iPhone 7, but works great on a samsung galaxy (android).

**Comment by payalord** [comment]
I don't have iPhone 7, but this sounds like on iPhone 7 or hammer version 1 doesn't work properly, or need to add some styles to prevent scroll while zoom is active maybe.
Have you tried Hammer version 2 example?
https://payalord.github.io/xzoom-sandbox/Hammer.jsV2/
https://github.com/payalord/xzoom-sandbox/tree/master/Hammer.jsV2

**Comment by payalord** [comment]
Hammer.jsV2 is not same lens example. But it shows integration with Hammer.js version 2. And is possible to test it's touch gestures on any mobile devices with this exampale.

**Comment by AnaGonzales** [comment]
great. it does sound like a hammer issue. i'll update and see if that fixes it. i was working on disabling scrolling as well. thanks!
