### ISSUE TITLE
how can I make the zoom result image bigger than the container

### ISSUE THREAD

**Issue by loroverde** [payalord/xZoom#62]
Hello
I would like the zoom result image to be bigger than the container image. 

I have made an example image to explain better my question.

Regards

![prev](https://user-images.githubusercontent.com/55993922/65939232-e710c880-e3ea-11e9-9ccd-b511a1910f61.jpg)

**Comment by payalord** [comment]
Try to use `zoomWidth` and `zoomHeight` parameters in options. More details are here: [Manual](https://github.com/payalord/xZoom/blob/master/doc/manual.md)
If this will not work, let me know.

**Comment by loroverde** [comment]
> Try to use `zoomWidth` and `zoomHeight` parameters in options. More details are here: [Manual](https://github.com/payalord/xZoom/blob/master/doc/manual.md)
> If this will not work, let me know.

Thanks so much, it runs perfectly !
