### ISSUE TITLE
Capturing current zoom scale

### ISSUE THREAD

**Issue by ghost** [payalord/xZoom#64]
Hello

Is there a way to capture the current image zoom scale and save it?

What I'm trying to accomplish:
- user zoom the image (in my case, mouse-over)
- user change the zoom scale with mouse scroll
- user closes the zoom with mouseleave
- **user go back to zoom the same image and xzoom remember the scale the image was when closed.**

So ideally on zoomclose I would like to detect the current zoom scale and overwrite "defaultScale" with it.

Is there a way to do this?

Thanks

**Comment by payalord** [comment]
Hi, sorry for long response. Here is how you can do it:
[PreserveScale example source](https://github.com/payalord/xzoom-sandbox/tree/master/PreserveScale)
[PreserveScale example demo](https://payalord.github.io/xzoom-sandbox/PreserveScale/)
