### ISSUE TITLE
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve '../images/xloading.gif' in 'C:\Users\fhsna\Projetos de software\lojafinal\loja\node_modules\xzoom\dist'

### ISSUE THREAD

**Issue by fhsnando** [payalord/xZoom#66]
Good morning!

In xzoom.css line 73

References a image wrong and when i use the laravel mix compiler return a error

Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve '../images/xloading.gif' in 'C:\Users\fhsna\Projetos de software\lojafinal\loja\node_modules\xzoom\dist'

**Comment by payalord** [comment]
For fast solution you can just place any loading indicator named `xloading.gif` generated as an example from here: https://icons8.com/preloaders/en/circular
Make sure you set up transparent background.

While later on I'll add original `xloading.gif` file to the source. Thanks.

**Comment by payalord** [comment]
Or actually here is that file is: https://github.com/payalord/xZoom/blob/master/example/images/xloading.gif

**Comment by payalord** [comment]
Reference for that image are fixed.
