### ISSUE TITLE
Add xzoom event on dynamic images 

### ISSUE THREAD

**Issue by AftabFalak** [payalord/xZoom#67]
Hi,
I have a commerce website and I am using this plugin on my side
the issue is that when I select the color difference for me menu all-new image in the "xzoom" and "xzoom-gallery" loaded. for xzoom it's working fine but when I clicked on one of the pics in "xzoom-thumbs" it the open the image on a new window.

I am again calling the   $('.xzoom, .xzoom-gallery').xzoom() after the images added but still the same issue

**Comment by payalord** [comment]
Not sure what exactly can broke xzoom in your project. But sounds like it might be a re-render issue. If dom elements has been re-rendered (removed and new ones added back) - that means the ones xzoom has been attached are removed and it will not work anymore. That is what usually happens in modern frontend frameworks.

Would be nice if you'll be able to provide an issue replication example.
Or you can also check https://github.com/payalord/xzoom-sandbox there is plenty examples available of different approaches where xzoom used. Maybe one of them can be helpful with your issue too.

**Comment by arifix** [comment]
@AftabFalak 

I faced exact same problem. That comment helps me a lot: https://github.com/payalord/xZoom/issues/52#issuecomment-420688785
