### ISSUE TITLE
Is it possible to use it with Vue.js?

### ISSUE THREAD

**Issue by medina325** [payalord/xZoom#69]
I'm trying really hard to make this work, but it seems like there is some sort of conflict that doesn't allow the zoom to work on a vue page.
The images and thumbs appear but the zoom itself no.
I saw some tips about how a frontend framework can affect the styles and break the zoom, but I'm not able to fix it.

Any suggestions?

**Comment by payalord** [comment]
Are you looking something like this?
https://github.com/payalord/xzoom-sandbox/tree/master/vue3

**Comment by medina325** [comment]
ooh good to know, thanks!

By the way I manage to make the plugin work in my Vue2.js page.

**My problem**: The problem was that the zoom (element with class .xzoom-source) was being messed up with so many styles that was hard to figure them all out.

**Solution**: set rootOutput to true (default value) so the zoom is attached to the end of the body tag, therefore no style is applied to it. The only caveat is that the zoom was "behind" everything else (that was hard to find out) so I had to add a z-index property bigger than the rest.

``` scss
 .xzoom-source, .xzoom-preview {
    z-index: 300; // other elements have 202 for z-index
    cursor: crosshair;
  }```

**Comment by payalord** [comment]
Glad `rootOutput` was a useful feature :+1: also you can change class names that xZoom uses via `options`. But not sure will that be helpful in your situation:
```
// xZoom options object:
{
  sourceClass: 'xzoom-source'
}
```

**Comment by medina325** [comment]
I'm actually trying to implement a navigation with arrow icons instead of just relying on the thumbs to navigate through the images.
Will I be able to do that with the methods available?

**Comment by payalord** [comment]
So you want to hide thumbs and navigate with arrow buttons/icons? Or you want to add slider to thumbs with arrows on both sides?

**Comment by medina325** [comment]
I wanted to add the navigation buttons and make the thumbs become nice dots (since there are different sized images).

I managed to implement the buttons logic like this:

``` javascript
const currentIndex = this.instance.gallery().index;
const previousImage = currentIndex-1 < 0 
                            ? $(".xzoom-gallery")[this.images.length-1]
                            : $(".xzoom-gallery")[currentIndex-1];

 // Bind click event to the previous image
 previousImage.click();
```
Where this.images is an array of my images paths.

To make the thumbs appear as dots, I think I got it.

PS.:  weirdly the gallery only returned the current index correctly, everything else was undefined.

**Comment by payalord** [comment]
Both `xzoom.gallery().ogallery` and `xzoom.gallery().cgallery` was `undefined`? Would be nice if you'll be able to share some replication example. But if problem solved, no problem.

**Comment by payalord** [comment]
I'll try to create proper example for this case with buttons in sandbox a little later.

**Comment by medina325** [comment]
> Both `xzoom.gallery().ogallery` and `xzoom.gallery().cgallery` was `undefined`? Would be nice if you'll be able to share some replication example. But if problem solved, no problem.

I created a Vue component that extends the plugin's functionality and can be used in any other view (of course). I initialize the plugin in the mounted method (it doesn't work if I initiliaze it in the created method) like so:

``` javascript
mounted() {      
      // Initialize xzoom
      this.instance = $(`.xzoom-${this.page}, .xzoom-gallery-${this.page}`).xzoom({
        scroll: true,
        defaultScale: 0.5,
        position: "inside"
      });
    },
```
You can notice the classes names are dynamic for it depends on the "page" prop, but even before I did that the gallery was behaving the way showed below:

![example_gallery](https://user-images.githubusercontent.com/56964034/118213898-d3d63380-b43c-11eb-9e36-d0fcbf71896f.jpg)

I console logged the gallery every time I clicked the next button:

``` javascript
console.log(this.instance.gallery());
```

You can see all three images in the gallery comes as undefined but the index is correct (previous index with which I calculate the next image to be shown).

**Comment by payalord** [comment]
What if the reason they are undefined is probably because dynamic vue update of dom? That is why we need to reinitialize xzoom's instance on every re-render tick unfortunately:

* https://vuejs.org/v2/api/#Vue-nextTick
* https://github.com/payalord/xzoom-sandbox/blob/a6a5bfb23fabfb352a8fdb497bc3b9ddcad5f8c6/vue3/src/components/xzoom.vue#L52
