### ISSUE TITLE
xzoom issue in ipad

### ISSUE THREAD

**Issue by prasad8801** [payalord/xZoom#7]
Iam  getting following errors in ipad . i have added hammer.js
xzoom.eventunbind();
Uncaught TypeError: Cannot read property 'eventunbind' of undefined

jQ(this).hammer().on("tap", function(event) {
Uncaught TypeError: jQ(...).hammer is not a function

https://sav.dotcomweavers.net/sportex-ar4145.html

can you help me on this.

**Comment by payalord** [comment]
Yes, i can help you.

Seems that you are not using any mobile touch gesture libraries. Like hammer.js or jQuery Mobile. Also you are not using Fancybox and Magnific popup too. In this case you don't need code related to them in your setup file. Change your **xzoom_setup.js** file content to this:
```javascript
(function ($) {
  $(document).ready(function() {
    $('.xzoom').xzoom({zoomWidth: 400, title: true,  Xoffset: 20});
  });
})(jQuery.noConflict());
```
This must make everything work fine.

BUT, honestly to provide smooth and nice support of touch experience on mobile and tablet devices, you'll better to use one of touch gesture library.

On https://payalord.github.io/xZoom i have used hammer.js version 1.0.5 and integrated xzoom with it. Check this page from mobile or iPad.

Also I'm planning to create some tutorials on how to easy setup xZoom and integrate it with touch gesture libraries for mobile devices, later.

P.S. xzoom v1.0.5 just released couple days ago. if you wish you can update it on your page :)

**Comment by payalord** [comment]
I have used jquery.hammer.min.js (hammer version 1.0.5), you can find it here: https://github.com/payalord/xZoom/tree/master/example/hammer.js/1.0.5

So, if you plan to use hammer.js here is how you need to modify **xzoom_setup.js** in your case:
```javascript
(function ($) {
    $(document).ready(function() {
        var xzoom = $('.xzoom').xzoom({zoomWidth: 400, title: true,  Xoffset: 20});

        //Integration with hammer.js
        var isTouchSupported = 'ontouchstart' in window;

        if (isTouchSupported) {
            //If touch device
            xzoom.eventunbind();
            
            $('.xzoom:first').hammer().on("tap", function(event) {
                event.pageX = event.gesture.center.pageX;
                event.pageY = event.gesture.center.pageY;
                var s = 1, ls;
    
                xzoom.eventmove = function(element) {
                    element.hammer().on('drag', function(event) {
                        event.pageX = event.gesture.center.pageX;
                        event.pageY = event.gesture.center.pageY;
                        xzoom.movezoom(event);
                        event.gesture.preventDefault();
                    });
                }
    
                xzoom.eventleave = function(element) {
                    element.hammer().on('tap', function(event) {
                        xzoom.closezoom();
                    });
                }
                xzoom.openzoom(event);
            });
        }
    });
})(jQuery.noConflict());
```

**Comment by payalord** [comment]
I assume that this issue is solved. If you have any other questions feel free to create new issue. Thanks.
