### ISSUE TITLE
Lens is not working - overlapping lens frame on hover 

### ISSUE THREAD

**Issue by viratg438** [payalord/xZoom#72]
![image](https://user-images.githubusercontent.com/89684569/131211813-65e0a9e1-73a4-456b-8ae0-138d06d06e57.png)

Hello Dear,
please solve it, I am trying to solve it but I can't, please check and update

**Comment by payalord** [comment]
Hi, there is a big chance that some of the css styles on your pages are affecting the plugin's one or it's behaviour. Please check the sandbox here: https://github.com/payalord/xzoom-sandbox you'll see a lot of working examples and specific use cases. Plus it's hard for me to identify what exactly wrong in your example based only on a screenshot.
