### ISSUE TITLE
Question - xzoom container size adjustability

### ISSUE THREAD

**Issue by gadnis** [payalord/xZoom#73]
Hi,

is it possible to adjust zoomed container size? Now by default it is same size as the image.

What I want is to hover small product thumb image (`50px x 50px`) and see a bigger size image next to the thumbnail (`250px x 250px`).

Is it possible with your plugin and how?

**Comment by payalord** [comment]
Have you tried option `zoomWidth` and `zoomHeight`? Let me know if it worked or not, thanks. Many other options available in [manual](https://github.com/payalord/xZoom/blob/master/doc/manual.md#options)
