### ISSUE TITLE
Either cursor is not working or Popup image window position is not right

### ISSUE THREAD

**Issue by ashiqsetu** [payalord/xZoom#76]
I need to show popup image window like first image but need cursor pointer like other image. But it's not working. If I set "zoomWidth: '10px" then popup image shows at right position but for this cursor pointer is gone. 

![1](https://user-images.githubusercontent.com/13822699/203264923-f318571a-418f-48c3-985c-5f2c580beca4.png)
![2](https://user-images.githubusercontent.com/13822699/203264966-4a187308-fa31-46e7-85f3-da42f57fe5d9.png)

Please have a look.

**Comment by payalord** [comment]
You can try this setup: https://github.com/payalord/xzoom-sandbox/tree/master/Popup

**Comment by ashiqsetu** [comment]
@payalord Thank you so much though late reply for both of us. I solved this next day of issue publishing.
