### ISSUE TITLE
Perfect plugin ，Why no arrows button

### ISSUE THREAD

**Issue by pufei889** [payalord/xZoom#77]
## Perfect plugin ，Why arrows button

**Comment by payalord** [comment]
xZoom doesn't include slider and arrow buttons for gallery icon images. Slider and arrows is possible to create separately with JS and CSS. xZoom itself is focused on zoom functionality. Still there is available a way to control or even to rewrite some of xZoom behavior with JS that is explained in the [manual](https://github.com/payalord/xZoom/blob/master/doc/manual.md) in Advanced Ways of Usage. And also more example in [xZoom Sandbox](https://github.com/payalord/xzoom-sandbox).
