### ISSUE TITLE
Add methods for custom code execution

### ISSUE THREAD

**Issue by Whip** [payalord/xZoom#8]
Great plugin. Can you add some methods where I could run my custom code on initialization or image hover? I'm not talking about the events provided.

**Comment by payalord** [comment]
Can you provide more details or example what you trying to accomplish? Because [Event methods](https://github.com/payalord/xZoom/blob/master/doc/manual.md#event-methods) api is exactly supposed to be the place where is possible to add some custom code

**Comment by Whip** [comment]
To be precise, I would like to create a tooltip like notification to inform users that they can scroll on the image to zoom in or out. That would be `instance.eventopen` method but I don't wish to override the default behavior.

**Comment by payalord** [comment]
Can you try to use this approach and let me know if this will work for you or not?
```javascript
var xzoom = $('.xzoom, .xzoom-gallery').xzoom(); //don't forget to add your options

// Or
// var xzoom = $('.xzoom').xzoom();


xzoom.eventclick = function(element) {

  //Remove next line and put your custom code here that will run on every zoom open event
  console.log('Zoom Opened');
  
  element.xon('click', function(event) {
    $('.xzoom:first').trigger('click');
  });
}

xzoom.eventleave = function(element) {
  element.xon('mouseleave', function() {

    //Remove next line and put your custom code here that will run on every zoom close event
    console.log('Zoom Closed');

    xzoom.closezoom();
  });
}
```

**Comment by Whip** [comment]
Yes. it does work as I wanted but with a lot of code than necessary. It would be great if you could create events that would fire on certain actions.

Thanks for this.

**Comment by payalord** [comment]
Yeah you right. I'll add more easy way to implement custom functions on events in future releases.

You welcome.
